### ISSUE TITLE
Creating a new service

### ISSUE THREAD

**Issue by LukeKerr** [Pushjet/Pushjet-Website#4]
When trying to create a new service via the docs part of the website it returns an error.

`{
    "error": {
        "id": 7,
        "message": "Missing argument service"
    }
}`

however all the arguments have been given.

`{
    "name": "Arts",
    "icon": "http://icons.iconarchive.com/icons/treetog/i/128/Floppy-Small-icon.png"
}`

**Comment by Mechazawa** [comment]
Looks like the docs were, for some reason, still using the old HTTP url instead of the new HTTPS one. This should be resolved now.

**Comment by Mechazawa** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Looks like the docs were, for some reason, still using the old HTTP url instead of the new HTTPS one. This should be resolved now.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJXBPyaAAoJENJKnc3chA9u8yQP/0wi2ComFpYaFs34tW7ynb08
qbTJbJGg48eFrsxzd8vzHWSlMX3yX6bC+tJTTDQGSk8SEJ5mYspyljZRRvz+iXQ/
/VXfT5AOVhlVcj65OgWpYy58pDPW81rGJkBaSP6sDL9gESG0XmQ6fM6s81DkIQp0
vmMTqjjq7Mhh5sEz5wPHaXPhX/B/DXZuGE5Rnein7735aqu9MPwuB+IW89Od8PTb
/o/pt9O3owBwAxwnMuO36qiPpwNZmvASCZxsEwb8xogMV2RZTBiYAHovcO8bODy8
X3C/wPfcNJYQHmd7dgdHnB4A17MlELEdTiI62sUPpUNpVvXLuHqAf9FTTrXgt7+I
xiHb2aTMg24hH7aa9O6C/YVJ/sMQI8TEyXK3zJeKiZXrkPpdPQvhltBhnDsf00/f
NHeX60PkfmM3b8dktlzXDRfJz4amaDptogSqw4O4VLGEM9oGFF+Z3b49Tvjz20xU
dLbFUKUqJ7GpAymnaOYz8faGF0YuUNDd+8m8JzFH8lTGiJVLIVgoUjBYm2wc/I20
YWiidEzCcY753N1QoSdwalbnGfvS7P6gZ2sGmbYF8C2ckwqmktwmd/pi0LaorTIR
PPNuDDWaSrzfAdyqT7uy1U2J+X/rB8lDYHCWJ4uPscSF4Al1AJGhadOHczXxM5K8
nSSZW8dpuYbU829xzA0X
=AJ7X
-----END PGP SIGNATURE——
